config/routes.rb
GithubSearch::Application.routes.draw do

  resources :searches do
    collection do 
      get 'log_in'
    end
  end

  root 'searches#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_action :set_client, only: [:log_in, :index]
  before_action :log_in, :unless => :got_token?, only: [:index]

  def log_in
    #github oauth
    redirect_to @github.authorize_url
  end

  def index

    unless session[:token_github].present?
      authorization_code = params[:code]
      access_token = @github.get_token authorization_code
      session[:token_github] = access_token.token
    end    

    respond_to do |format|
      format.html
      format.json { render json: GithubDatatable.new(view_context, session[:token_github])}
    end

  end

  def got_token?
    session[:token_github].present? || params[:code].present?
  end

  def set_client
    @github = Github.new client_id: ENV['GITHUB_CLIENT_ID'], client_secret: ENV['GITHUB_CLIENT_SECRET']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubSearch</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/index.html.erb
<h1>Git Hub Search!</h1>

<ol>
  <li>First type your query in the search box for the repository.</li>
  <li>After searching, you can sort by stars by clicking it's table heading.</li>
  <li>You can also filter your search results by language using the input box above it's heading.</li>
</ol>

<p>Note: Hit "enter" after typing your query to apply the search or filter.</p>

<table id="searches" class='datatable' data-source="<%= searches_url(format: "json") %>">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>       
      </tr>   
      <tr>
        <th>Repo</th>
        <th>Language</th>
        <th>Stars</th>
      </tr>

    </thead>

    <tbody>

    </tbody>
</table>